# Generated by Django 4.0.3 on 2022-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_ar',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description_en',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
