# Generated by Django 4.0.3 on 2022-06-02 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('description_ar', models.CharField(blank=True, max_length=5000, null=True)),
                ('description_en', models.CharField(blank=True, max_length=5000, null=True)),
                ('cover', models.CharField(blank=True, max_length=300, null=True)),
                ('poster', models.CharField(blank=True, max_length=300, null=True)),
                ('trailer', models.CharField(blank=True, max_length=300, null=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('releaseYear', models.IntegerField(default=1888, validators=[django.core.validators.MaxValueValidator(2999), django.core.validators.MinValueValidator(1888)])),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5160), django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
        ),
    ]
