# Generated by Django 4.0.3 on 2022-06-02 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(21840), django.core.validators.MinValueValidator(0)]),
        ),
    ]
