# Generated by Django 4.0.3 on 2022-06-02 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='no',
            new_name='number',
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(33), django.core.validators.MinValueValidator(1)])),
                ('title_ar', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('poster', models.CharField(blank=True, max_length=300, null=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.series')),
            ],
        ),
    ]
