# Generated by Django 4.0.3 on 2022-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_no_episode_number_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movies', models.ManyToManyField(blank=True, null=True, to='core.movie')),
                ('series', models.ManyToManyField(blank=True, null=True, to='core.series')),
            ],
        ),
    ]
