# Generated by Django 4.0.3 on 2022-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='movies',
            field=models.ManyToManyField(to='core.movie'),
        ),
        migrations.AlterField(
            model_name='section',
            name='series',
            field=models.ManyToManyField(to='core.series'),
        ),
    ]
