# Generated by Django 4.0.3 on 2022-06-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_section_movies_alter_section_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.series'),
            preserve_default=False,
        ),
    ]
