# Generated by Django 4.0.3 on 2022-06-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_episode_season_alter_episode_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
    ]
