# Generated by Django 4.0.3 on 2022-06-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_episode_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.series'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
