# Generated by Django 4.0.3 on 2022-06-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_episode_season_episode_series_delete_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='seasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.series'),
        ),
    ]
