# Generated by Django 4.0.3 on 2022-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_series_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='seasons',
        ),
        migrations.AddField(
            model_name='series',
            name='seasons',
            field=models.ManyToManyField(to='core.series'),
        ),
    ]
