# Generated by Django 4.0.3 on 2022-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_series_seasons_series_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releaseYear',
            new_name='release_year',
        ),
        migrations.AlterField(
            model_name='series',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, to='core.series'),
        ),
    ]
