# Generated by Django 4.0.3 on 2022-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_actor_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='core.genre'),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='core.genre'),
        ),
    ]
