# Generated by Django 4.0.3 on 2022-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_comment_episode_comment_movie_comment_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
    ]
