# Generated by Django 4.0.3 on 2022-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='core.series'),
        ),
    ]
