# Generated by Django 4.0.3 on 2022-06-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_comment_episode_alter_comment_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='genre',
            new_name='genres',
        ),
    ]
