# Generated by Django 4.0.3 on 2022-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_genre_movie_genres_rename_genre_series_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
    ]
