# Generated by Django 4.0.3 on 2022-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_episode_video_alter_episode_cover_alter_movie_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
