# Generated by Django 4.0.3 on 2022-06-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_movie_actors_movie_director_delete_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(blank=True, to='core.actor'),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.director'),
        ),
    ]
