# Generated by Django 4.0.3 on 2022-06-16 09:04

import core.models.movie
import core.models.series
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_series_actors_series_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='cover',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, default='logo2.svg', null=True, upload_to=core.models.movie.upload_to),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='logo2.svg', null=True, upload_to=core.models.movie.upload_to),
        ),
        migrations.AlterField(
            model_name='section',
            name='movies',
            field=models.ManyToManyField(blank=True, to='core.movie'),
        ),
        migrations.AlterField(
            model_name='section',
            name='series',
            field=models.ManyToManyField(blank=True, to='core.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(blank=True, default='logo2.svg', null=True, upload_to=core.models.series.upload_to),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, default='logo2.svg', null=True, upload_to=core.models.series.upload_to),
        ),
    ]
