# Generated by Django 4.0.3 on 2022-06-20 16:17

import core.models.movie
import core.models.series
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_episode_cover_alter_movie_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='releaseYear',
            new_name='release_year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to=core.models.movie.upload_to),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to=core.models.movie.upload_to),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to=core.models.series.upload_to),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to=core.models.series.upload_to),
        ),
    ]
