# Generated by Django 2.1.15 on 2022-06-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220616_0928'),
        ('core', '0036_rename_releaseyear_series_release_year_and_more'),
    ]

    operations = [
    ]
