# Generated by Django 2.1.15 on 2022-06-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_section_order'),
        ('core', '0037_merge_20220621_1234'),
    ]

    operations = [
    ]
