# Generated by Django 4.0.3 on 2022-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_artist_created_at_alter_artist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='cdn_cover',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='cdn_video',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cdn_video',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
