# Generated by Django 4.0.3 on 2022-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_episode_cdn_cover_episode_cdn_video_movie_cdn_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_low_q',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_medium_q',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_low_q',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_medium_q',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
