# Generated by Django 4.0.3 on 2022-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_movie_streaming_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streaming_server',
            options={'verbose_name_plural': 'Streaming Servers'},
        ),
        migrations.AddField(
            model_name='streaming_server',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
