# Generated by Django 4.0.3 on 2022-07-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_streaming_server_options_streaming_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='streaming_server',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.streaming_server'),
        ),
    ]
