# Generated by Django 4.0.3 on 2022-07-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_movie_streaming_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='streaming_server',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.streaming_server'),
        ),
    ]
